name: sebo
favicon: null
layout_spectrum: 0.8217206499539316
typography_spectrum: 0.24247039668262005
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.75
  lightness: 0.75
  saturation: 0.375
  rhythmicContrast: 0.75
purpose: []
